name: update contributors cronjob

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 20 1 * *"
  push:
    branches: 
      - 'add-contributors'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: "Install prerequisites"
        run: |
          pip3 install -r requirements.txt
      - run: |
          ./hack/contributors.py
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
